name: Bonjour
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/cicd-lectures/gitpod:latest
      options: --user=root
    steps:
      - uses: actions/checkout@v3 
      - run : sudo apt-get update && sudo apt-get install cowsay
      - run: cat README.md
      - run: |
          cat README.md | cowsay
          echo "meuh" | cowsay
