name: menu_server_intégration_continue
on:
  - push
jobs:
  dire_bonjour:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/cicd-lectures/gitpod:latest
      options: --user=root
    steps:
      - uses: actions/checkout@v3 
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '17.0.6'
      - uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.6
      - run: mvn compile
      - run: mvn package
      